# Generated by Django 3.0 on 2021-05-26 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CreateTask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnnotationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassID', models.IntegerField(default=0)),
                ('UserID', models.IntegerField()),
                ('LastUpdate', models.DateTimeField(auto_now=True)),
                ('DataInstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTask.TextDataInstance')),
                ('TaskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textanno', to='CreateTask.Task')),
            ],
        ),
    ]
